### ISSUE TITLE
new app: something for surveys

### ISSUE THREAD

**Issue by aep** [kraudcloud/apps#2]
we want some open source app where you can create surveys, similar to typeform.

**Comment by karitham** [comment]
was setting up limesurvey but it's a php horror

```yaml
version: '3'
name: limesurvey

x-kraud-ui:
  label: "Limesurvey - survey"
  description: |
    Limesurvey is the number one open-source survey software.

    Advanced features like branching and multiple question types make it a valuable partner for survey-creation.

    Whether you are creating a simple questionnaire or working on sophisticated surveys with complex validation rules,
    conditional logic and quota management: We provide you with all the tools you need.

    So you can achieve your survey goals quickly.

  logo_url: "https://www.limesurvey.org/images/limesurvey/svg/logo_limesurvey_head.svg"
  ext_url: "https://limesurvey.org/"
  config:
    ingress:
      INGRESS:
        label: "web domain"
        description: "domain where the app will be hosted at"
        protocol: "https"
        default: "limesurvey.*"
        required: true

    volumes:
      DATABASE:
        label: "database"
        description: "Volume where database will be located"
        default: "lime_mysql"

    environment:
      DB_PASSWORD:
        label: "database password"
        description: "password for the database"
        required: true
      LIMESURVEY_PASSWORD:
        label: "limesurvey password"
        description: "password for the admin limesurvey user"
        required: true
      ADMIN_EMAIL:
        label: "admin email"
        description: "email for the admin limesurvey user"
        required: true

volumes:
  lime_db:
    name: ${DATABASE:-lime_db}
    driver: "local"

services:
  limesurvey:
    image: martialblog/limesurvey
    container_name: limesurvey
    restart: always
    labels:
      - kr.ingress.8080=${INGRESS:-https://limesurvey.*}
    ports:
      - 8080:8080
    environment:
      - DB_TYPE=pgsql
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD?db password is required}
      - DB_NAME=limesurvey
      - DB_USERNAME=limesurvey
      - ADMIN_USER=admin
      - ADMIN_NAME=Admin
      - ADMIN_PASSWORD=example
      - ADMIN_EMAIL=${ADMIN_EMAIL?admin email is required}
      - PUBLIC_URL=${INGRESS:-https://limesurvey.*}

  db:
    image: postgres:10-alpine
    container_name: db
    restart: always
    volumes:
      - ${DATABASE-lime_db}:/var/lib/postgresql
    environment:
      - POSTGRES_USER=limesurvey
      - POSTGRES_DB=limesurvey
      - POSTGRES_PASSWORD=${DB_PASSWORD?db password is required}
```
I can't get it to work, will try to find something else
